/* File produced with RAWTEX Gimp plugin v1.06
   Written by Franck Charlet. */

#define _BARBED_WIRE_V_TEXTURE_WIDTH 64
#define _BARBED_WIRE_V_TEXTURE_REAL_WIDTH 64
#define _BARBED_WIRE_V_TEXTURE_HEIGHT 64
#define _BARBED_WIRE_V_TEXTURE_REAL_HEIGHT 64
#define _BARBED_WIRE_V_TEXTURE_FORMAT 4
#define _BARBED_WIRE_V_TEXTURE_MIPMAPS 0
#define _BARBED_WIRE_V_TEXTURE_SWIZZLE 1

#define _BARBED_WIRE_V_PALETTE_FORMAT 3
#define _BARBED_WIRE_V_PALETTE_COLORS (7 / 8)
#define _BARBED_WIRE_V_PALETTE_MASK 0xf
#define _BARBED_WIRE_V_MIPMAPS_OFFSET0 0
