/* File produced with RAWTEX Gimp plugin v1.06
   Written by Franck Charlet. */

#define _BOARD_FE_TEXTURE_WIDTH 64
#define _BOARD_FE_TEXTURE_REAL_WIDTH 64
#define _BOARD_FE_TEXTURE_HEIGHT 64
#define _BOARD_FE_TEXTURE_REAL_HEIGHT 64
#define _BOARD_FE_TEXTURE_FORMAT 4
#define _BOARD_FE_TEXTURE_MIPMAPS 0
#define _BOARD_FE_TEXTURE_SWIZZLE 1

#define _BOARD_FE_PALETTE_FORMAT 3
#define _BOARD_FE_PALETTE_COLORS (16 / 8)
#define _BOARD_FE_PALETTE_MASK 0xf
#define _BOARD_FE_MIPMAPS_OFFSET0 0
