/* File produced with RAWTEX Gimp plugin v1.06
   Written by Franck Charlet. */

#define _CAMO_2_TEXTURE_WIDTH 32
#define _CAMO_2_TEXTURE_REAL_WIDTH 32
#define _CAMO_2_TEXTURE_HEIGHT 32
#define _CAMO_2_TEXTURE_REAL_HEIGHT 32
#define _CAMO_2_TEXTURE_FORMAT 4
#define _CAMO_2_TEXTURE_MIPMAPS 0
#define _CAMO_2_TEXTURE_SWIZZLE 1

#define _CAMO_2_PALETTE_FORMAT 3
#define _CAMO_2_PALETTE_COLORS (10 / 8)
#define _CAMO_2_PALETTE_MASK 0xf
#define _CAMO_2_MIPMAPS_OFFSET0 0
