/* File produced with RAWTEX Gimp plugin v1.06
   Written by Franck Charlet. */

#define _METAL_RAIL7_TEXTURE_WIDTH 32
#define _METAL_RAIL7_TEXTURE_REAL_WIDTH 32
#define _METAL_RAIL7_TEXTURE_HEIGHT 16
#define _METAL_RAIL7_TEXTURE_REAL_HEIGHT 16
#define _METAL_RAIL7_TEXTURE_FORMAT 4
#define _METAL_RAIL7_TEXTURE_MIPMAPS 0
#define _METAL_RAIL7_TEXTURE_SWIZZLE 1

#define _METAL_RAIL7_PALETTE_FORMAT 3
#define _METAL_RAIL7_PALETTE_COLORS (5 / 8)
#define _METAL_RAIL7_PALETTE_MASK 0xf
#define _METAL_RAIL7_MIPMAPS_OFFSET0 0
