/* File produced with RAWTEX Gimp plugin v1.06
   Written by Franck Charlet. */

#define _RAILLING_NDU_TEXTURE_WIDTH 64
#define _RAILLING_NDU_TEXTURE_REAL_WIDTH 64
#define _RAILLING_NDU_TEXTURE_HEIGHT 64
#define _RAILLING_NDU_TEXTURE_REAL_HEIGHT 64
#define _RAILLING_NDU_TEXTURE_FORMAT 4
#define _RAILLING_NDU_TEXTURE_MIPMAPS 0
#define _RAILLING_NDU_TEXTURE_SWIZZLE 1

#define _RAILLING_NDU_PALETTE_FORMAT 3
#define _RAILLING_NDU_PALETTE_COLORS (16 / 8)
#define _RAILLING_NDU_PALETTE_MASK 0xf
#define _RAILLING_NDU_MIPMAPS_OFFSET0 0
